[project]
name = "image-retrieval"
version = "0.0.1"
description = "Create an image vector database and query it using text."
readme = "README.md"
authors = [
    { name = "asha-lily" },
]
requires-python = ">=3.12"
dependencies = [
    "config>=0.5.1",
    "chromadb>=1.1.0",
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.10",
    "langchain-chroma>=0.2.6",
    "open-clip-torch>=3.2.0",
    "pandas>=2.2.3",
    "pydantic>=2.11.9"
]

[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle
    "I",   # isort
    "ANN", # flake8 type annotations
    "RUF", # ruff-specific rules
]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"